# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\wolfeite\projectPy\frame\httpserver\gui\UI\UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI(object):
    def setupUi(self, UI):
        UI.setObjectName("UI")
        UI.resize(511, 610)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/66964/.designer/backup/Data/Assets/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UI.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(UI)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 471, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 400, 54, 12))
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(20, 420, 421, 121))
        self.textEdit.setObjectName("textEdit")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 201, 91))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 50, 41, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(100, 50, 41, 21))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_8.setObjectName("label_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 100, 201, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_11.setGeometry(QtCore.QRect(150, 50, 41, 21))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setGeometry(QtCore.QRect(100, 50, 41, 21))
        self.pushButton_12.setObjectName("pushButton_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_10.setObjectName("label_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 200, 201, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 50, 41, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 50, 41, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_12.setObjectName("label_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(240, 200, 201, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 50, 41, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 50, 41, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_14.setObjectName("label_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 300, 201, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_13.setGeometry(QtCore.QRect(150, 50, 41, 21))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_14.setGeometry(QtCore.QRect(100, 50, 41, 21))
        self.pushButton_14.setObjectName("pushButton_14")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_13.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_18.setObjectName("label_18")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 10, 421, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 20, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_10.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(200, 20, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(200, 50, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 54, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 54, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_9.setGeometry(QtCore.QRect(340, 20, 61, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab)
        self.pushButton_15.setGeometry(QtCore.QRect(240, 370, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 50, 201, 91))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_16.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_20.setObjectName("label_20")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox.setGeometry(QtCore.QRect(50, 50, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 190, 201, 91))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_17.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_22.setObjectName("label_22")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 50, 141, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(250, 50, 201, 91))
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_18.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_23 = QtWidgets.QLabel(self.groupBox_9)
        self.label_23.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_24.setObjectName("label_24")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_3.setGeometry(QtCore.QRect(50, 50, 141, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(250, 190, 201, 91))
        self.groupBox_10.setObjectName("groupBox_10")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_19.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_25 = QtWidgets.QLabel(self.groupBox_10)
        self.label_25.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_10)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_26.setObjectName("label_26")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_4.setGeometry(QtCore.QRect(50, 50, 141, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 330, 201, 91))
        self.groupBox_11.setObjectName("groupBox_11")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_20.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_27 = QtWidgets.QLabel(self.groupBox_11)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_11)
        self.label_28.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_28.setObjectName("label_28")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_5.setGeometry(QtCore.QRect(50, 50, 141, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(250, 400, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 54, 21))
        self.label_5.setObjectName("label_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_6.setGeometry(QtCore.QRect(70, 20, 351, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(30, 70, 54, 21))
        self.label_29.setObjectName("label_29")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(70, 70, 351, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 100, 391, 161))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(40, 290, 54, 16))
        self.label_30.setObjectName("label_30")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 310, 381, 151))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_16.setGeometry(QtCore.QRect(260, 470, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_17.setGeometry(QtCore.QRect(350, 470, 75, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.tabWidget.addTab(self.tab_5, "")
        UI.setCentralWidget(self.centralWidget)

        self.retranslateUi(UI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UI)

    def retranslateUi(self, UI):
        _translate = QtCore.QCoreApplication.translate
        UI.setWindowTitle(_translate("UI", "旋钮装置上位机"))
        self.label_6.setText(_translate("UI", "接收："))
        self.groupBox.setTitle(_translate("UI", "顺时针旋转"))
        self.pushButton_2.setText(_translate("UI", "清空"))
        self.pushButton.setText(_translate("UI", "测试"))
        self.label_7.setText(_translate("UI", "指令："))
        self.label_8.setText(_translate("UI", "数量："))
        self.groupBox_2.setTitle(_translate("UI", "逆时针旋转"))
        self.pushButton_11.setText(_translate("UI", "清空"))
        self.pushButton_12.setText(_translate("UI", "测试"))
        self.label_9.setText(_translate("UI", "指令："))
        self.label_10.setText(_translate("UI", "数量："))
        self.groupBox_3.setTitle(_translate("UI", "单击"))
        self.pushButton_3.setText(_translate("UI", "清空"))
        self.pushButton_4.setText(_translate("UI", "测试"))
        self.label_11.setText(_translate("UI", "指令："))
        self.label_12.setText(_translate("UI", "数量："))
        self.groupBox_4.setTitle(_translate("UI", "双击"))
        self.pushButton_5.setText(_translate("UI", "清空"))
        self.pushButton_6.setText(_translate("UI", "测试"))
        self.label_13.setText(_translate("UI", "指令："))
        self.label_14.setText(_translate("UI", "数量："))
        self.groupBox_5.setTitle(_translate("UI", "长按"))
        self.pushButton_13.setText(_translate("UI", "清空"))
        self.pushButton_14.setText(_translate("UI", "测试"))
        self.label_17.setText(_translate("UI", "指令："))
        self.label_18.setText(_translate("UI", "数量："))
        self.groupBox_6.setTitle(_translate("UI", "链接状态"))
        self.label.setText(_translate("UI", "硬件链接：链接成功"))
        self.label_2.setText(_translate("UI", "物联网链接：链接成功"))
        self.label_3.setText(_translate("UI", "ID："))
        self.label_4.setText(_translate("UI", "展示端："))
        self.pushButton_9.setText(_translate("UI", "保存"))
        self.pushButton_15.setText(_translate("UI", "保存配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UI", "旋钮配置"))
        self.groupBox_7.setTitle(_translate("UI", "顺时针旋转"))
        self.label_19.setText(_translate("UI", "颜色："))
        self.label_20.setText(_translate("UI", "模式："))
        self.comboBox.setItemText(0, _translate("UI", "单亮"))
        self.comboBox.setItemText(1, _translate("UI", "常亮"))
        self.groupBox_8.setTitle(_translate("UI", "单击"))
        self.label_21.setText(_translate("UI", "颜色："))
        self.label_22.setText(_translate("UI", "模式："))
        self.comboBox_2.setItemText(0, _translate("UI", "单亮"))
        self.comboBox_2.setItemText(1, _translate("UI", "常亮"))
        self.groupBox_9.setTitle(_translate("UI", "逆时针旋转"))
        self.label_23.setText(_translate("UI", "颜色："))
        self.label_24.setText(_translate("UI", "模式："))
        self.comboBox_3.setItemText(0, _translate("UI", "单亮"))
        self.comboBox_3.setItemText(1, _translate("UI", "常亮"))
        self.groupBox_10.setTitle(_translate("UI", "双击"))
        self.label_25.setText(_translate("UI", "颜色："))
        self.label_26.setText(_translate("UI", "模式："))
        self.comboBox_4.setItemText(0, _translate("UI", "单亮"))
        self.comboBox_4.setItemText(1, _translate("UI", "常亮"))
        self.groupBox_11.setTitle(_translate("UI", "长按"))
        self.label_27.setText(_translate("UI", "颜色："))
        self.label_28.setText(_translate("UI", "模式："))
        self.comboBox_5.setItemText(0, _translate("UI", "单亮"))
        self.comboBox_5.setItemText(1, _translate("UI", "常亮"))
        self.pushButton_10.setText(_translate("UI", "保存设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("UI", "灯光配置"))
        self.label_5.setText(_translate("UI", "Key："))
        self.comboBox_6.setItemText(0, _translate("UI", "--选择API--"))
        self.label_29.setText(_translate("UI", "Api："))
        self.label_30.setText(_translate("UI", "反馈："))
        self.pushButton_16.setText(_translate("UI", "清理"))
        self.pushButton_17.setText(_translate("UI", "测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("UI", "API测试"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UI = QtWidgets.QMainWindow()
    ui = Ui_UI()
    ui.setupUi(UI)
    UI.show()
    sys.exit(app.exec_())
